### ISSUE TITLE
Data.Date.Locale functions return UTC values

### ISSUE THREAD

**Issue by purefn** [purescript-contrib/purescript-datetime#11]
`hourOfDay` and other functions use the UTC functions, e.g.  `getUTCHours`, instead of locale specific functions like `getHours`.

**Comment by garyb** [comment]
Oops! Thanks for the report, I'll fix this and make a new release later today.

**Comment by garyb** [comment]
Fixed in 182c6c69956f1f7a156a5a6d68bcb01b62b50ab6
